# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9190b46cb5405d59797f471a5ae4b2844d92f4e081e7de650e8da191617564d20bb1ff0c38b89ab0f06c55cae637f591c9472c49c519d545f803f32c3c02cf55

test:
  secret_key_base: 915f67571ebad5f72931dd2e44ddb7b304fa468e96db0a61c0d6c21ef0cb5f837eacea2d5968b1987fd395a8fcf221b31b3191aae8aa513e7411d119f499ce8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
